install:
  - ps: appveyor DownloadFile "https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/appveyor.ps1"
  - ps: .\appveyor.ps1 "bootstrap" -verbose
  # install Package Control
  # - ps: .\appveyor.ps1 "install_package_control" -verbose

build: off

test_script:

  # run tests with test coverage report
  - ps: .\appveyor.ps1 "run_tests" -coverage -verbose
  # testing syntax_test files
  # - ps: .\appveyor.ps1 "run_syntax_tests" -verbose
  # - ps: .\appveyor.ps1 "run_syntax_compatibility" -verbose

after_test:
  - "SET PYTHON=C:\\Python33"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install coverage==4.5.4 codecov==2.0.15
  - codecov
